version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: galette-sausage-db
    environment:
      POSTGRES_DB: galette_sausage
      POSTGRES_USER: galette
      POSTGRES_PASSWORD: sausage123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galette -d galette_sausage"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: