name: Claude PR Review
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - main

jobs:
  claude-review:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trigger_phrase: "@claude-review"
          direct_prompt: "Review this PR comprehensively and report all issues found."
          custom_instructions: |
            You are reviewing a pull request for the galette-sausage-monorepo project.
            
            IMPORTANT: You MUST check for and report ALL issues including:
            
            1. **Commit Messages**:
               - Check ALL commit messages for:
                 - Spelling mistakes and typos
                 - Vague or meaningless messages (e.g., "fix", "update", "changes")
                 - Poor grammar
                 - Lack of clarity about what was changed
            
            2. **Spelling and Grammar**: Check ALL text for spelling mistakes, typos, and grammatical errors in:
               - Code comments
               - Documentation files (*.md)
               - String literals
               - Variable/function names
               - PR title and description
            
            3. **Code Quality**:
               - Best practices violations
               - Code style consistency
               - Potential bugs or logic errors
               - Security vulnerabilities
               - Performance issues
            
            4. **Documentation**:
               - Missing or unclear documentation
               - Outdated information
               - Formatting issues
            
            Be EXTREMELY thorough and critical. DO NOT approve if there are ANY issues.
            List ALL problems found, no matter how minor.
            If commit messages are poor quality, this alone is reason to request changes.
      - name: Comment on PR to trigger Claude
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@claude-review Please review this PR for all issues including commit messages, spelling, grammar, and code quality.'
            })