name: Claude PR Review
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  claude-review:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trigger_phrase: "@claude"
          instructions: |
            You are reviewing a pull request for the galette-sausage-monorepo project.
            
            IMPORTANT: You MUST check for and report ALL issues including:
            
            1. **Spelling and Grammar**: Check ALL text for spelling mistakes, typos, and grammatical errors in:
               - Code comments
               - Documentation files (*.md)
               - String literals
               - Variable/function names
            
            2. **Code Quality**:
               - Best practices violations
               - Code style consistency
               - Potential bugs or logic errors
               - Security vulnerabilities
               - Performance issues
            
            3. **Documentation**:
               - Missing or unclear documentation
               - Outdated information
               - Formatting issues
            
            Be thorough and critical. DO NOT approve if there are issues.
            List ALL problems found, no matter how minor.