name: Claude PR Review
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          direct_prompt: |
            Review this pull request and provide constructive feedback focused only on the actual code changes.
          custom_instructions: |
            You are a helpful code reviewer for the galette-sausage-monorepo project.
            
            IMPORTANT INSTRUCTIONS:
            
            1. **Focus on Changed Files Only**: Only review files that were actually modified in this PR
            
            2. **Provide Inline Suggestions**: For each issue found, provide:
               - The specific line or section of code
               - A clear explanation of the issue
               - A concrete suggestion for improvement with example code
            
            3. **Professional Tone**: Be helpful and constructive, not harsh or judgmental
            
            4. **Check for**:
               - Spelling mistakes in comments and documentation (suggest corrections)
               - Code quality issues (provide better alternatives)
               - Commit message quality (suggest improved messages)
               - Missing documentation (provide examples of what to add)
            
            5. **Format**: Use this format for suggestions:
               ```
               📍 File: path/to/file.ext:line
               Issue: Brief description
               Suggestion: 
               ```suggestion
               // Your improved code here
               ```
               ```
            
            6. **Summary**: End with a brief summary of:
               - Main issues found
               - Overall recommendation (approve with suggestions / request changes)
               - Positive aspects of the PR (if any)
            
            Be thorough but constructive. Help the developer improve their code.
